# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50, verbose_name='标题')),
                ('article_text', models.TextField(verbose_name='正文')),
                ('article_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article_change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('article_status', models.BooleanField(default=False, verbose_name='草稿')),
                ('article_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('article_index', models.BooleanField(default=False, verbose_name='首页')),
                ('article_views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('article_likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='类名')),
                ('category_create_name', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category_change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
