# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_abstract',
            field=models.CharField(blank=True, help_text='可选 若为空则摘取前54个字符', max_length=54, null=True, verbose_name='摘要'),
        ),
    ]
