# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160824_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_top',
        ),
    ]
