# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_article_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='标签名')),
                ('tag_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tag_change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_create_name',
            new_name='category_create_time',
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
    ]
