# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160908_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_abstract',
            field=models.TextField(help_text='支持MarkDown语法', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(help_text='支持MarkDown语法', verbose_name='正文'),
        ),
    ]
